### ISSUE TITLE
Impossible to Get a the new store after Regenerate for testing.

### ISSUE THREAD

**Issue by clems4ever** [fasthttp/session#10]
In the context of testing a handler performing a `Regenerate`, I'd like to be able to `Get` the new store (after regenerate) from the testing code but that does not work because the `Get` method retrieves the old instance of store instead.

This issue is due to the fact that `Get` retrieves the session ID from the request cookie https://github.com/fasthttp/session/blob/efbf5440438a6407d3829d52000146d25ccab291/session.go#L154 but after the `Regenerate` we only set the response cookie here: https://github.com/fasthttp/session/blob/efbf5440438a6407d3829d52000146d25ccab291/cookie.go#L41. Therefore, when doing a `Get` again afterwards in the testing code, the initial store is retrieved instead of the new one. What would you think about setting the new sessionID in the request cookie as we do when deleting the cookie here: https://github.com/fasthttp/session/blob/efbf5440438a6407d3829d52000146d25ccab291/cookie.go#L64 ?

@savsgio , what do you think?

**Comment by savsgio** [comment]
When you call `session.Regenerate()` gets the new store, it's not necessary to call `session.Get`again.

**Comment by clems4ever** [comment]
Yes, the tested code can access the new Store but not the testing code unless you return the store out of the handler for testing purposes which is bad. Anyway, now that my PR is merged, it fixes the issue. Thanks.
