### ISSUE TITLE
is this production ready?

### ISSUE THREAD

**Issue by hiqsociety** [fasthttp/session#14]
can you provide more example? i realised there are a lot of things that can be done for configuration setting but it's not written.

how to make the cookie domain be .domain.com? it's domain.com now.

any example on how to do cross cookie domain?

**Comment by savsgio** [comment]
Did you configure the domain configuration? 

https://github.com/fasthttp/session/blob/master/types.go#L20

**Comment by savsgio** [comment]
and yes, the session is ready for production.
