### ISSUE TITLE
github.com/gomodule/redigo also / instead.

### ISSUE THREAD

**Issue by hiqsociety** [fasthttp/session#18]
the current redis implementation with go-redis is very limited. possible to change to github.com/gomodule/redigo
?

**Comment by savsgio** [comment]
Why do you need that?

Now, all implementation of redis provider are complete, independently of the backend library.
Also go-redis has more performance than redigo.

**Comment by savsgio** [comment]
If you need some change or improv, please open a PR.

**Comment by hiqsociety** [comment]
i ended up modifying go-sessions from kataras. I realised the code written for fasthttp is not how valyala would write it though... it's very complicated and not very elegant etc. I'm quite surprised valyala didn't write the session for this as it's quite important.

i'm sure fasthttp/sessions will be better in future. thanks and appreciate the hard work anyway.

**Comment by savsgio** [comment]
What do you mean about "fasthttp/session wil be better in the future??

**Comment by hiqsociety** [comment]
I went through go-sessions from kataras for 1 day and realised it was not designed for fasthttp in the first place

Possible for you to make a boiler plate for redigo? I just need the basic connector etc and I'll complete the rest of it.

**Comment by savsgio** [comment]
This software does not have any kind of relationship with the whole Kataras environment.

At first, session has been developed with redigo, but i had say you that go-redis has more performance and cover all functionality of session.
Also, you couldn't use the redis conector directly. I don't understand why do you need to implement it here.

if you need the redis connector directly, create your own instance and use it.

**Comment by hiqsociety** [comment]
OK i've checked the code for redis but I realised it's still using the built in cache of cookie memory area from valyala/fasthttp

does that need fixing?
