### ISSUE TITLE
time.Now() with UnixNano

### ISSUE THREAD

**Issue by 979156** [fasthttp/session#21]
Hi @savsgio , it's me again.
I set expiration as **10 * time.Minute** and my provider(Docker container with image mariadb/10.4.12-bionic ) stored it as 600.
but setting 'last_active' as nano made SQLGC's where clausemismatch, so my session doesn't keep alive. Below is my session table.

mariadb root@localhost:dev> select * from session;
+----------------------------------+--------------------------------------------------------------------------------------------------+---------------------+--------------+
| id                               | data                                                                                             |         last_active |   expiration |
|----------------------------------+--------------------------------------------------------------------------------------------------+---------------------+--------------|
| nqMriPTLKiLRguvobaRoaRBdWgGWtzxB | gaFEkoKjS2V5xANmb2+lVmFsdWWjYmFygqNLZXnEGl9fc3RvcmU6ZXhwaXJhdGlvbjp0eVlTQl9fpVZhbHVl0wAAAIuyyXAA | **1588249643693065881** |          **600** |
+----------------------------------+--------------------------------------------------------------------------------------------------+---------------------+--------------+
1 row in set
Time: 0.004s
mariadb root@localhost:dev>

**Comment by savsgio** [comment]
I will re-upload the version v2.0.2!

**Comment by savsgio** [comment]
Done! 😉
