### ISSUE TITLE
Setting Expiration to -1 causes runtime error

### ISSUE THREAD

**Issue by DanielAtwood** [fasthttp/session#25]
Using the example provided and setting`cfg.Expiration` to `-1` causes the following error to appear when loading any of the pages.
`Error 1264: Out of range value for column 'expiration' at row 1`

Setting it to `0` turns it into a session cookie. While any positive number works as intended.

Visiting `/getAll` still outputs to console so I'm assuming it must be part of the saving process.
```go
defer func() {
	if err := serverSession.Save(ctx, store); err != nil {
		ctx.Error(err.Error(), fasthttp.StatusInternalServerError)
	}
}()
```
## Behavior
| Value | Expected | Reality |
|------|-----------|--------|
|-1|Session|error|
|0|no-expire|Session|
|>0|time|time|

### Environment
|Name|Version|
|-|-|
|Mac OSX|10.15.4 |
|fasthttp|1.14.0|
|fasthttp router|1.2.2|
|fasthttp session|2.1.1|

**Comment by savsgio** [comment]
Hi @DanielAtwood,

Which provider are you using?


Thanks for your issue!

**Comment by DanielAtwood** [comment]
|Provider|-1|0|time.duration|
|---|---|---|---|
|Memory| session|session|future timestamp|
|MySQL|error|session|future timestamp|

**Comment by savsgio** [comment]
I've been fixed it, so i will release a new version with the bugfix! 😉
