### ISSUE TITLE
MYSQL drops table on init, on purpose?

### ISSUE THREAD

**Issue by Fenny** [fasthttp/session#26]
Hi @savsgio, I noticed that when we use the MYSQL provider the table gets dropped on initialization ( https://github.com/fasthttp/session/blob/master/providers/mysql/provider.go#L13 ).

So it's not possible to save session data in case of a server crash, I'm wondering if this is a design choice?

Thank you!

**Comment by savsgio** [comment]
Hi @Fenny,

Sorry for delayed answer.

It's a bug, maybe could be added a flag in the provider config (MySQL, Postgre and Sqlite3) to reset or not the session table when starts.

Could you make the PR, please.
