### ISSUE TITLE
int value not stored

### ISSUE THREAD

**Issue by tgarm** [fasthttp/session#29]
It seems the __int__ value is not stored correctly in session.
When serving with the following test code, __GET__ from __/__, the value of __session['incr']__ is expected to increment each time, but it always keep the same.

The code uses __sqlite3__ as the provider.

Is the code written wrongly or session does not support __int__ type, or it is a bug of the session provider?

Please have a look at this code:

```go
package main

import (
    "fmt"
    "log"

    "github.com/fasthttp/router"
    "github.com/fasthttp/session/v2"
    "github.com/fasthttp/session/v2/providers/sqlite3"
    "github.com/valyala/fasthttp"
)

var serverSession *session.Session

func incrHandler(ctx *fasthttp.RequestCtx) {
    store, err := serverSession.Get(ctx)
    if err != nil {
        ctx.Error(err.Error(), fasthttp.StatusInternalServerError)
        return
    }   
    defer func() {
        if err := serverSession.Save(ctx, store); err != nil {
            ctx.Error(err.Error(), fasthttp.StatusInternalServerError)
        }   
    }() 

    cval,ok := store.Get("incr").(int)
    if ok {
        cval++
    }else{
        log.Println("get incr failed,cval",cval)
        cval = 1 
    }   

    store.Set("incr", cval)

    sessionID := store.GetSessionID()
    ctx.SetBodyString(fmt.Sprintf("Session(%s) SET: incr='%d' --> OK", sessionID, store.Get("incr").(int)))
}

func init() {
    provider, err := sqlite3.New(sqlite3.NewConfigWith("test.db", "session"))
    if err != nil {
        log.Fatal(err)
    }

    cfg := session.NewDefaultConfig()
    cfg.EncodeFunc = session.Base64Encode
    cfg.DecodeFunc = session.Base64Decode
    serverSession = session.New(cfg)

    if err = serverSession.SetProvider(provider); err != nil {
        log.Fatal(err)
    }
}

func main() {
    r := router.New()
    r.GET("/", incrHandler)

    addr := "0.0.0.0:8086"
    log.Println("Now Listen on %s",addr)

    err := fasthttp.ListenAndServe(addr, r.Handler)
    if err != nil {
        log.Fatal(err)
    }
}

```

**Comment by thomasvvugt** [comment]
Can you test whether int64 works?
I however use Redis as the session provider, but that did the trick for me.

**Comment by tgarm** [comment]
Just tried, int64 works.

```go
    cval,ok := store.Get("incr").(int64)
    if ok {
        cval++
    }else{
        log.Println("get incr failed,cval",cval)
        cval = 1 
    }   

    store.Set("incr", cval)

    sessionID := store.GetSessionID()
    ctx.SetBodyString(fmt.Sprintf("Session(%s) SET: incr='%d' --> OK", sessionID, store.Get("incr").(int64)))
```

> Can you test whether int64 works?
> I however use Redis as the session provider, but that did the trick for me.

**Comment by savsgio** [comment]
Hi @tgarm and @thomasvvugt,

Sorry for delayed answer, i was in vacation.

The base enconder/decoder of session is `msgp` that's encodes `int` values as `int64, independently of the chosen provider.
You could see that here: https://github.com/tinylib/msgp/blob/master/msgp/write_bytes.go#L359

So the "trick" or the correct way is to always use `int64` type.

**Comment by thomasvvugt** [comment]
Hi @savsgio, thanks for your response. 
I hope you had a great vacation! 
Thanks for the clarification regarding the use of `int64` as the correct data type.
