### ISSUE TITLE
Please immediately declare the copyright and the license statement ! !

### ISSUE THREAD

**Issue by phachon** [fasthttp/session#3]
## Please be sure to include a author copyright notice and a license notice！！！

My project: https://github.com/phachon/fasthttpsession （I found that you have a PR in my project !）

**Comment by savsgio** [comment]
Yes, I took your project like base to improve and add enhancements to reduce extra allocations the maximum possible.
I did too much modifications in project, so now it don't looks like your project.

Anyway I have no problem in recognizing that I took your project as a basis.

Before start this, I made a PR to your repository, improving the Go Report Card, but I saw that you didn't answer and i though you didn't maintain more the sessions. And I decided to take your project as a basis.

So Don't Worry, I'm going to add you into LICENSE.

**Comment by phachon** [comment]
`I did too much modifications in project, so now it don't looks like your project.` 

Ok， I welcome anyone to make changes on the basis of my project.
But please respect the original author！At least you should mark where you copied it！

I didn't see any meaning of your apology. Is it so hard to say sorry?

I feel very depressed！

**Comment by savsgio** [comment]
Yes, of course, sorry for not added you into LICENSE before.

**Comment by savsgio** [comment]
I have just added you into license.
