### ISSUE TITLE
IDEA: Set custom session ID

### ISSUE THREAD

**Issue by ManelSomili** [fasthttp/session#30]
It'll be really cool if you could add the capability to set a custom session like we have in PHP with the session_id() function.
This is especially useful in a non-browser context, like server-to-server communication with a need for session management based on a custom identifier.

**Comment by ManelSomili** [comment]
Never mind, found that I can supply my own session ID generator function.

**Comment by ManelSomili** [comment]
On second thought, a custom session ID generator doesn't do what I thought it would. 
A SetSessionID function would be nice.

**Comment by savsgio** [comment]
Hi @ManelSomili,

Do you mean to set a custom session id for *one user session* and the others user sessions continue using the session id generator?

**Comment by circledata** [comment]
Hi @savsgio , Thank you for your prompt response.

Yes, I meant being able to set a custom session id for a single user. I'm working on an app where I need to be able to retrieve a user's session using their phone number as the session ID. 

The feature is really good for apps like WhatApp chatbots, USSD applications, or server-to-server communications where a user attribute is the intended identifier for a session.

**Comment by savsgio** [comment]
Hi @ManelSomili @circledata,

You could use [store.SetSessionId(...)](https://pkg.go.dev/github.com/fasthttp/session/v2?tab=doc#Store.SetSessionID) (**before save the user session**) the set a custom session id for a single user.

Sorry for delayed answer.
