### ISSUE TITLE
Redis: Multi-instance app session expiration inconsistency (v2)

### ISSUE THREAD

**Issue by james-d-elliott** [fasthttp/session#32]
I have not yet 100% confirmed the version this occurred in, but I think it was the upgrade from 1.1.8 to 2.0.0. 

Basically if you use the redis provider in a mutli-instance app in something like kubernetes the redis provider does not seem to obtain the correct session expiration (after using Store.SetExpiration() and Session.Save())from the redis store, leading to the situation where your session expiration is not the same between sessions.

I have also played with using Traefik to enable sticky load balancing. In this instance as soon as the load balancer cookie expires, and the client his a new pod, it appears as if the second pod is completely unaware of the change to the expiration.

To me it makes sense the session expiration should be available to all instances, but maybe I'm incorrect?

**Comment by james-d-elliott** [comment]
I have a feeling this diff to the expiration key is the cause:

https://github.com/fasthttp/session/blob/v1.1.8/const.go#L14
https://github.com/fasthttp/session/blob/v2.2.5/store.go#L10

**Comment by james-d-elliott** [comment]
After some investigation and testing I can confirm that change is the one actually causing the issue. Everything works fine if I force it to just be the following:

```go
const expirationAttrKey = "__store:expiration__"
```

**Comment by james-d-elliott** [comment]
https://github.com/authelia/session/commit/f5e9a6faf6828fde6d32ab39ad4b30783b376599

This commit is what we're using downstream to fix it. However I'm waiting to hear back from you to make a PR. I think logically it should be a configurable that defaults back to a random value - i.e. if config string isn't blank/empty/whitespace-only use it to configure the var, otherwise use the already randomly generated string. Though it's possible there's a method already I couldn't find any.

**Comment by savsgio** [comment]
Hi @james-d-elliott,

You're right, well seen!! it was my mistake.

Could you make a PR to fix it, please??

**Comment by james-d-elliott** [comment]
@savsgio Yes I can, what's the preferred method? A static value? Or something that can be configured?

**Comment by savsgio** [comment]
A static value is ok
