### ISSUE TITLE
Redis Cluster/Sentinel

### ISSUE THREAD

**Issue by james-d-elliott** [fasthttp/session#37]
From what I can tell from the upstream library, you need to instantiate a client with NewClusterClient/NewSentinelClient in order to setup connections to these types, I've not confirmed this. But was wondering if you either knew before I worked on supporting something like this, and if you had a preference for how we would set it up.

I think realistically it would be better to make it their own providers since the options are vastly different for [Sentinel](https://github.com/go-redis/redis/blob/master/sentinel.go#L21-L70) and for [Cluster](https://github.com/go-redis/redis/blob/master/cluster.go#L26-L80) configurations.

**Comment by james-d-elliott** [comment]
@savsgio did you have an opinion on this at all?

**Comment by savsgio** [comment]
Hi @james-d-elliott,

Sorry for delayed answer.

The configuration of these clients are different, so you could create a separate providers for thats clients.

So if you want you could make a PR and i will review it.

**Comment by james-d-elliott** [comment]
It's no worries, I saw you were busy with stuff in the other fasthttp repos! I figured you saw it and forgot so just gave you a friendly ping.

Also that's what I thought the preference would be and makes sense. I'll look at implementing sometime soon.

**Comment by james-d-elliott** [comment]
For anyone interested in redis cluster please see the third paragraph of https://github.com/fasthttp/session/pull/38#issuecomment-786913928 and my commit on our downstream maintenance repo (please note this repo is not going to be maintained, it's just here so we can implement features rapidly) https://github.com/authelia/session/commit/db6b8521dd7c5412e180b538933b84092d5a39fa
