### ISSUE TITLE
Session ID generator panic

### ISSUE THREAD

**Issue by james-d-elliott** [fasthttp/session#43]
Just letting you know we solved this issue upstream by implementing our own session ID generator, but figure there is likely an underlying cause you may want to investigate:

https://github.com/authelia/authelia/issues/2349

Basically looks like under some conditions is it causes an index out of range panic, I suspect heavy load.

**Comment by savsgio** [comment]
Hi @james-d-elliott,

Thanks you so much. I'll try to research about that 😉 

Sorry for my delayed answer!

**Comment by james-d-elliott** [comment]
No worries at all. They were the first user to ever experience it, not sure I can say for certain what the cause is but according to some recent research it's because you're using rand.NewSource potentially:

https://pkg.go.dev/math/rand#NewSource:

"Unlike the default Source used by top-level functions, this source is not safe for concurrent use by multiple goroutines. "

**Comment by savsgio** [comment]
Hi @james-d-elliott,

Fixed!! 🎉  (Sorry for waiting)

Thanks!

**Comment by james-d-elliott** [comment]
No worries on my end, we just utilized the session id  generator func. :)
