### ISSUE TITLE
Widen api a bit

### ISSUE THREAD

**Issue by dj8yfo** [fasthttp/session#44]
Hi, @savsgio !
Can you add a version of Get that doesn't attempt to regenerate a new id and returns a *Store only if it is present? Or make getSessionID method public?

I can wait for a late reply and submit a pr, if needed.
![2021-11-05_12-32](https://user-images.githubusercontent.com/26653921/140498033-37caa2bf-d2ad-4d63-b6e3-76d256291227.png)

**Comment by savsgio** [comment]
Hi @dj8yfo,

Could you make a PR that's make public `getSessionID()` function, please.
