### ISSUE TITLE
ioor when calling Save

### ISSUE THREAD

**Issue by james-d-elliott** [fasthttp/session#46]
Using the memory provider a couple users are reporting an index out of range issue. Wondering if you have any idea what we can do to figure out the underlying cause?

https://github.com/authelia/authelia/issues/3751

**Comment by savsgio** [comment]
Hi @james-d-elliott,

Sorry for my delayed answer!

I try ti fix it in a few days!

Thanks and sorry!

**Comment by james-d-elliott** [comment]
No stress, is it obviously a bug? I couldn't figure out how it was occurring.

**Comment by savsgio** [comment]
Hi @james-d-elliott,

Fixed on [v2.4.14](https://github.com/fasthttp/session/releases/tag/v2.4.14). 

If the bug persist, reopen the issue, please! 😉 

Thanks you so much!

**Comment by james-d-elliott** [comment]
No worries! Thanks for fixing it. We didn't see it for a long time I think the chance of it occurring again is small, but if we do I will. I also generally recommend people utilize the redis provider in production anyway.

**Comment by savsgio** [comment]
Yes it is, the memory provider is mostly for testing. For production better use redis or any other provider!
