### ISSUE TITLE
Allow setting cookie secure flag when requests are served through trusted proxies.

### ISSUE THREAD

**Issue by clems4ever** [fasthttp/session#5]
@savsgio , when fasthttp server is behind a proxy and there is no TLS link between the proxy and the server because let say the server and the proxy are on the same host, the secure flag of the cookie should legitimately be set to `true` to enhance security.
I propose to add a configuration attribute called `TrustedProxies` being a list of strings being known and trusted IPs of proxies in order to mimic the behavior of the Express framework as described in this documentation: http://expressjs.com/en/guide/behind-proxies.html.

So what I propose is to check whether  `the connection is over TLS` || (`the remote IP is a trusted proxy` && `X-Forwarde-Proto is set to https`) by modifying the following line:
https://github.com/fasthttp/session/blob/1f4f9f473dc6b346c8e2ab5af02da4f49b9a6fc5/cookie.go#L37

Would that sound reasonable to you?

**Comment by clems4ever** [comment]
Here is the proposal: https://github.com/fasthttp/session/pull/6

**Comment by savsgio** [comment]
Thanks for your PR!
